(function(){'use strict';
let d;try{d=JSON.parse(sessionStorage.getItem('sr_invoice_payload')||'null')}catch(e){}
const page=document.getElementById('invoicePage'),err=document.getElementById('error'),btn=document.getElementById('pdfBtn');
if(!d){page.style.display='none';err.style.display='block';btn.disabled=true;return}
const txt=(id,v)=>document.getElementById(id).textContent=String(v??'');
const money=v=>Number(v||0).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2});
d.invKm=d.invKm||0;['name','street','cityFull','iban','bic','home','away','place','gameDate','invKm'].forEach(k=>txt(k,d[k]));['fee','travel','hotel','other','total'].forEach(k=>txt(k,money(d[k])));txt('travel2',money(d.travel));txt('cityDen',d.city||'');txt('bottomDate',d.gameDate||'');
function b64bytes(b64){const bin=atob(b64),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return a}
function pdfFromJpeg(jb,w,h){const enc=new TextEncoder(),parts=[],off=[0];let pos=0;const add=x=>{const b=typeof x==='string'?enc.encode(x):x;parts.push(b);pos+=b.length};const obj=(n,b)=>{off[n]=pos;add(n+' 0 obj\n'+b+'\nendobj\n')};add('%PDF-1.4\n%PDFGEN\n');obj(1,'<< /Type /Catalog /Pages 2 0 R >>');obj(2,'<< /Type /Pages /Kids [3 0 R] /Count 1 >>');obj(3,'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>');off[4]=pos;add('4 0 obj\n<< /Type /XObject /Subtype /Image /Width '+w+' /Height '+h+' /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length '+jb.length+' >>\nstream\n');add(jb);add('\nendstream\nendobj\n');const stream='q\n595.28 0 0 841.89 0 0 cm\n/Im0 Do\nQ\n';obj(5,'<< /Length '+enc.encode(stream).length+' >>\nstream\n'+stream+'endstream');const xref=pos;add('xref\n0 6\n0000000000 65535 f \n');for(let i=1;i<=5;i++)add(String(off[i]).padStart(10,'0')+' 00000 n \n');add('trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n'+xref+'\n%%EOF');return new Blob(parts,{type:'application/pdf'})}
function makePdf(){btn.disabled=true;btn.textContent='PDF wird erstellt …';const im=document.getElementById('template');const go=()=>{try{const c=document.createElement('canvas');c.width=1654;c.height=2339;const x=c.getContext('2d');x.drawImage(im,0,0,c.width,c.height);const sx=c.width/210,sy=c.height/297;x.fillStyle='#111';x.textBaseline='top';x.font=Math.round(4.55*sy)+'px Arial';const draw=(id,left,top)=>x.fillText(document.getElementById(id).textContent,left*sx,top*sy);draw('name',54,53.7);draw('street',54,64.4);draw('cityFull',54,75.0);draw('iban',27,85.6);draw('bic',154,85.6);draw('home',13,115.8);draw('away',113,115.8);draw('place',33,129.4);draw('gameDate',122,129.4);draw('invKm',67.5,172.3);draw('cityDen',13,257.9);draw('bottomDate',68.5,257.9);const right=190.8*sx;function dm(id,top,bold){x.font=(bold?'bold ':'')+Math.round(4.55*sy)+'px Arial';const t=document.getElementById(id).textContent;x.fillText(t,right-x.measureText(t).width,top*sy)}dm('fee',143.7);dm('travel',157.9);dm('travel2',172.3);dm('hotel',186.6);dm('other',200.8);dm('total',215.2,true);const jb=b64bytes(c.toDataURL('image/jpeg',0.97).split(',')[1]);const blob=pdfFromJpeg(jb,c.width,c.height);const url=URL.createObjectURL(blob);location.href=url}catch(e){alert('PDF konnte nicht erstellt werden: '+e.message);btn.disabled=false;btn.textContent='PDF erstellen'}};if(im.complete)go();else{im.onload=go;im.onerror=()=>{alert('Vorlage konnte nicht geladen werden.');btn.disabled=false;btn.textContent='PDF erstellen'}}}
btn.addEventListener('click',makePdf);
})();
